[routers]

  [routers.demo]
  hostname = "demo.mt.lv"
  port = 8728
  username = "admin"
  password = ""

  [routers.demo2]
  hostname = "demo2.mt.lv"
  port = 8728
  username = "admin"
  password = ""
